# ============================================================
# submit_<<EXPERIMENT_NAME>>.py
# Generated by the submit-to-cea skill
#
# Three sections are marked EXPERIMENT CONFIGURATION — these
# are the only parts that change per experiment.
# ============================================================
import numpy as np
import json
import os
import argparse
import logging
import time
from datetime import datetime
import utils.sequence_utils as su
from pulser.backend import QPUBackend
from pulser.backend.remote import BatchStatus, JobStatus


# ====================================================================
# BOILERPLATE — identical across all CEA experiments
# ====================================================================

def setup_logging(log_dir="logs"):
    os.makedirs(log_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = os.path.join(log_dir, f"submission_{timestamp}.log")
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
        handlers=[logging.FileHandler(log_file), logging.StreamHandler()],
    )
    return logging.getLogger(__name__)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Submit <<EXPERIMENT_NAME>> jobs to Pasqal, CEA or Jade"
    )
    parser.add_argument(
        "--backend",
        choices=["pasqal", "cea", "jade"],
        required=True,
        help="Choose backend: pasqal, cea or jade",
    )
    parser.add_argument(
        "--n-shots",
        type=int,
        default=<<N_SHOTS>>,
        help="Number of shots per job (default: <<N_SHOTS>>)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Output directory for results",
    )
    parser.add_argument(
        "--job-index",
        type=int,
        default=None,
        help="Single job index to submit (array job mode). If not set, all jobs run sequentially.",
    )
    parser.add_argument(
        "--max-wait-hours",
        type=float,
        default=12.0,
        help="Max hours to wait for QPU availability (default: 12.0)",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=0,
        help="Job index to resume from, 0-indexed (default: 0)",
    )
    return parser.parse_args()


def setup_pasqal_connection(logger):
    # Environment variables only — deliberately not the shared pasqal_auth
    # policy the local skills use. This file runs inside a container on a
    # compute node: no keyring service, and a credentials file on a shared
    # cluster filesystem is worse than one in the job environment.
    missing = [v for v in ("PASQAL_USERNAME", "PASQAL_PASSWORD", "PASQAL_PROJECT_ID")
               if not os.getenv(v)]
    if missing:
        raise SystemExit(
            f"Missing credentials in the job environment: {', '.join(missing)}. "
            "Export them in the submission script before launching.")
    try:
        from pulser_pasqal import PasqalCloud
        connection = PasqalCloud(
            username=os.getenv("PASQAL_USERNAME"),
            password=os.getenv("PASQAL_PASSWORD"),
            project_id=os.getenv("PASQAL_PROJECT_ID"),
            region=os.getenv("PASQAL_REGION"),
        )
        logger.info("Connected to Pasqal Cloud")
        device = connection.fetch_available_devices()[os.getenv("PASQAL_DEVICE", "FRESNEL_CAN1")]
        device.print_specs()
        return connection, device
    except Exception as e:
        logger.error(f"Failed to setup Pasqal connection: {e}", exc_info=True)
        raise


def wait_for_qpu(connection, max_wait_hours, logger):
    max_wait_s = max_wait_hours * 3600
    elapsed = 0
    interval = 300
    while elapsed < max_wait_s:
        try:
            available = connection.fetch_available_devices()
            if available:
                qpu_key = next(iter(available))
                device = available[qpu_key]
                logger.info(f"QPU '{qpu_key}' available after {elapsed/60:.0f} min wait")
                return connection, device
            logger.warning(
                f"QPU in maintenance (empty device list). Retrying in {interval}s... "
                f"({elapsed/60:.0f}/{max_wait_hours*60:.0f} min elapsed)"
            )
        except Exception as e:
            logger.warning(f"Connection error while checking QPU: {e}. Retrying in {interval}s...")
        time.sleep(interval)
        elapsed += interval
        interval = min(interval * 1.5, 900)
    raise RuntimeError(f"QPU not available after {max_wait_hours}h of waiting")


def setup_cea_connection(logger, max_wait_hours=4.0):
    try:
        from pulser_myqlm import PulserQLMConnection
        connection = PulserQLMConnection(timeout=300)
        logger.info("Connected to PulserQLM")
        connection, device = wait_for_qpu(connection, max_wait_hours, logger)
        logger.info(f"QPU device acquired: {device}")
        return connection, device
    except Exception as e:
        logger.error(f"Failed to setup CEA connection: {e}", exc_info=True)
        raise


def setup_jade_connection(logger, max_wait_hours=4.0):
    try:
        from pulser_myqlm import PulserQLMConnection
        hostname = os.getenv("JADE_QLMAAS_HOSTNAME")
        port = os.getenv("JADE_QLMAAS_PORT")
        kwargs = {"timeout": 300}
        if hostname:
            kwargs["hostname"] = hostname
        if port:
            kwargs["port"] = int(port)
        connection = PulserQLMConnection(**kwargs)
        logger.info("Connected to Jade PulserQLM")
        connection, device = wait_for_qpu(connection, max_wait_hours, logger)
        return connection, device
    except Exception as e:
        logger.error(f"Failed to setup Jade connection: {e}", exc_info=True)
        raise


def poll_job_status(connection, batch_id, logger, poll_interval=30, max_poll_time=3600):
    job_ids = connection._get_job_ids(batch_id)
    logger.info(f"  QLMaaS job ID(s): {job_ids}")
    elapsed = 0
    last_statuses = {}
    while elapsed < max_poll_time:
        try:
            progress = connection._query_job_progress(batch_id)
            for jid, (status, _) in progress.items():
                if status != last_statuses.get(jid):
                    logger.info(f"  Job {jid}: status={status.name} (after {elapsed}s)")
                    last_statuses[jid] = status
            batch_status = connection._get_batch_status(batch_id)
            if batch_status in (BatchStatus.DONE, BatchStatus.ERROR, BatchStatus.CANCELED):
                logger.info(f"  Batch final status: {batch_status.name} (after {elapsed}s)")
                return batch_status
        except Exception as poll_err:
            logger.warning(f"  Poll error after {elapsed}s: [{type(poll_err).__name__}] {poll_err}")
        time.sleep(poll_interval)
        elapsed += poll_interval
    logger.error(f"  Polling timed out after {max_poll_time}s. Last statuses: {last_statuses}")
    raise TimeoutError(f"Job polling timed out after {max_poll_time}s")


def run_with_retry(qpu, job, para_seq, connection, max_wait_hours, logger, jade_kwargs=None):
    max_retries = 5
    base_delay = 60
    for attempt in range(max_retries):
        try:
            submit_time = datetime.now()
            logger.info(f"  Submitting (attempt {attempt+1}/{max_retries}) at {submit_time.isoformat()}")
            results = qpu.run(job_params=[job], wait=False)
            submit_elapsed = (datetime.now() - submit_time).total_seconds()
            logger.info(f"  Submitted in {submit_elapsed:.1f}s, batch_id: {results.batch_id}")
            batch_status = poll_job_status(connection, results.batch_id, logger)
            if batch_status == BatchStatus.ERROR:
                raise RuntimeError(f"Batch ended with ERROR (batch_id={results.batch_id})")
            if batch_status == BatchStatus.CANCELED:
                raise RuntimeError(f"Batch CANCELED (batch_id={results.batch_id})")
            elapsed = (datetime.now() - submit_time).total_seconds()
            logger.info(f"  Job completed in {elapsed:.1f}s")
            return results, qpu, connection
        except Exception as e:
            elapsed = (datetime.now() - submit_time).total_seconds()
            logger.warning(
                f"Job failed (attempt {attempt+1}/{max_retries}) after {elapsed:.1f}s: "
                f"[{type(e).__name__}] {e}"
            )
            if attempt == max_retries - 1:
                logger.error(f"All {max_retries} attempts exhausted. Last error: {repr(e)}")
                raise
            delay = base_delay * (attempt + 1)
            logger.info(f"Waiting {delay}s before retry...")
            time.sleep(delay)
            from pulser_myqlm import PulserQLMConnection
            conn_kwargs = jade_kwargs if jade_kwargs else {"timeout": 300}
            connection = PulserQLMConnection(**conn_kwargs)
            connection, device = wait_for_qpu(connection, max_wait_hours, logger)
            qpu = QPUBackend(para_seq, connection)
    raise RuntimeError("Unreachable")


def submit_pasqal_jobs(
    list_para_seq, params, connection, n_shots, output_dir, name, logger, start_index=0
):
    try:
        batch_ids_path = os.path.join(output_dir, "batch_ids")
        os.makedirs(batch_ids_path, exist_ok=True)
        batch_id_dict = {}
        for k, para_seq in enumerate(list_para_seq):
            qpu = QPUBackend(para_seq, connection)
            job_list = [
                {"runs": n_shots, "variables": {"params": params["times"][l]}}
                for l in range(len(params["times"]))
            ][start_index:]
            results = qpu.run(job_list)
            batch_id_dict[k] = results.batch_id
            logger.info(f"Batch {k+1} submitted with ID: {results.batch_id}")
        batch_file = os.path.join(batch_ids_path, f"{name}.json")
        with open(batch_file, "w") as fp:
            json.dump(batch_id_dict, fp, indent=2)
        logger.info(f"Batch IDs saved to {batch_file}")
        return batch_id_dict
    except Exception as e:
        logger.error(f"Failed to submit Pasqal jobs: {e}", exc_info=True)
        raise


def submit_cea_jobs(
    list_para_seq,
    params,
    connection,
    n_shots,
    output_dir,
    name,
    logger,
    job_index=None,
    max_wait_hours=4.0,
    start_index=0,
):
    try:
        n_total = len(params["times"])
        if job_index is not None:
            logger.info(f"Single job mode: submitting job {job_index}/{n_total}")
        else:
            logger.info(f"Submitting {n_total - start_index} jobs to CEA QPU")

        batch_ids_path = os.path.join(output_dir, "batch_ids")
        os.makedirs(batch_ids_path, exist_ok=True)

        indices = [job_index] if job_index is not None else range(start_index, n_total)

        for k, para_seq in enumerate(list_para_seq):
            logger.info(f"Submitting batch {k+1}/{len(list_para_seq)}")
            qpu = QPUBackend(para_seq, connection)
            job_list = [
                {"runs": n_shots, "variables": {"params": params["times"][l]}}
                for l in range(n_total)
            ]

            # Pre-flight: verify 4 ns clock alignment
            clock_period_ns = 4
            misaligned = [
                (idx, job_list[idx]["variables"]["params"])
                for idx in indices
                if round(job_list[idx]["variables"]["params"]) % clock_period_ns != 0
            ]
            if misaligned:
                logger.warning(
                    f"  Pre-flight: {len(misaligned)} jobs have durations not aligned "
                    f"to {clock_period_ns} ns clock period: {misaligned[:5]}..."
                )
            else:
                logger.info(
                    f"  Pre-flight: all {len(list(indices))} jobs pass clock-period alignment check"
                )

            for job_idx in indices:
                job = job_list[job_idx]
                t_ns = job["variables"]["params"]
                logger.info(f"Batch {k+1}, Job {job_idx+1}/{n_total} (params={t_ns})")

                results, qpu, connection = run_with_retry(
                    qpu, job, para_seq, connection, max_wait_hours, logger
                )

                batch_id = results.batch_id
                fetched = None
                for fetch_attempt in range(5):
                    try:
                        fetched = connection._fetch_result(batch_id, None)
                        break
                    except Exception as fetch_err:
                        logger.warning(f"  Result fetch attempt {fetch_attempt+1}/5 failed: {fetch_err}")
                        time.sleep(10)
                if fetched is None:
                    raise RuntimeError(f"Could not fetch results for batch {batch_id} after 5 attempts")

                sampled_result = fetched[-1]
                result_data = {
                    "k": k,
                    "job_idx": job_idx,
                    "batch_id": batch_id,
                    "variables": job["variables"],
                    "results": sampled_result.final_bitstrings,
                    "full_results": sampled_result.to_abstract_repr(),
                }

                if job_index is not None:
                    out_path = os.path.join(batch_ids_path, f"{name}_job_{job_idx}.json")
                    with open(out_path, "w") as f:
                        json.dump(result_data, f)
                    logger.info(f"Job {job_idx} saved to {out_path}")
                else:
                    out_path = os.path.join(batch_ids_path, f"{name}.json")
                    with open(out_path, "a") as f:
                        json.dump(result_data, f)
                        f.write("\n")

                logger.info(f"Batch {k+1}, Job {job_idx+1} completed with ID: {results.batch_id}")
                time.sleep(30)

        logger.info("CEA job submission complete.")
    except Exception as e:
        logger.error(f"Failed to submit CEA jobs: {e}", exc_info=True)
        raise


# ====================================================================
# EXPERIMENT CONFIGURATION — edit these three functions only
# ====================================================================

def prepare_sequence_parameters(logger, device=None):
    """Define the parameter sweep for <<EXPERIMENT_NAME>>.

    Returns a dict with at minimum:
      "N"       — number of qubits
      "times"   — list of parameter values mapped to the Pulser variable "params",
                  must all be multiples of 4 ns if representing durations
      "version" — experiment name string (used in output filenames)
    Plus any fixed physical parameters needed by the builder function.
    """
    logger.info("Preparing sequence parameters")

    # Parameter sweep — replace with actual values
    times = <<PARAMETER_VALUES_LIST>>

    params = {
        "N": <<N_QUBITS>>,
        "times": times,
        "version": "<<EXPERIMENT_NAME>>",
        <<FIXED_PARAMS_DICT_ENTRIES>>
    }

    logger.info(
        f"Parameters: N={params['N']}, n_times={len(params['times'])}, "
        f"range=[{min(params['times'])}, {max(params['times'])}]"
    )
    return params


def build_sequence(params, device, logger):
    """Build the parametric Pulser sequence for <<EXPERIMENT_NAME>>."""
    try:
        logger.info(f"Building parametric sequence (N={params['N']})")
        return su.<<BUILDER_FUNCTION_NAME>>(
            N=params["N"],
            device=device,
            <<BUILDER_CALL_ARGS>>
        )
    except Exception as e:
        logger.error(f"Failed to build sequence: {e}", exc_info=True)
        raise


def save_parameters(params, output_dir, logger):
    """Save parameter list to JSON; return experiment name."""
    try:
        name = params["version"]
        params_path = os.path.join(output_dir, "params")
        os.makedirs(params_path, exist_ok=True)
        param_file = os.path.join(params_path, f"{name}.json")
        with open(param_file, "w") as fp:
            json.dump(<<PARAMS_JSON_FIELDS>>, fp, indent=2)
        logger.info(f"Parameters saved to {param_file}")
        return name
    except Exception as e:
        logger.error(f"Failed to save parameters: {e}", exc_info=True)
        raise


# ====================================================================
# MAIN
# ====================================================================

def main():
    args = parse_args()
    logger = setup_logging()
    if args.output_dir is None:
        args.output_dir = "<<OUTPUT_DIR>>"

    logger.info("=" * 80)
    logger.info(
        f"Starting <<EXPERIMENT_NAME>> | backend: {args.backend} | output: {args.output_dir}"
    )
    logger.info("=" * 80)

    try:
        if args.backend == "pasqal":
            connection, device = setup_pasqal_connection(logger)
        elif args.backend == "jade":
            connection, device = setup_jade_connection(logger, max_wait_hours=args.max_wait_hours)
        else:  # cea
            connection, device = setup_cea_connection(logger, max_wait_hours=args.max_wait_hours)

        params = prepare_sequence_parameters(logger, device=device)
        para_seq = build_sequence(params, device, logger)
        name = save_parameters(params, args.output_dir, logger)
        logger.info(f"Experiment name: {name}")

        if args.backend == "pasqal":
            submit_pasqal_jobs(
                [para_seq], params, connection, args.n_shots,
                args.output_dir, name, logger, start_index=args.start_index,
            )
        else:  # cea or jade
            submit_cea_jobs(
                [para_seq], params, connection, args.n_shots,
                args.output_dir, name, logger,
                job_index=args.job_index,
                max_wait_hours=args.max_wait_hours,
                start_index=args.start_index,
            )

        logger.info("=" * 80)
        logger.info("All jobs submitted successfully!")
        logger.info("=" * 80)

    except Exception as e:
        logger.error("=" * 80)
        logger.error(f"Job submission failed: {e}")
        logger.error("=" * 80)
        raise


if __name__ == "__main__":
    main()
